server:
  port: 8081
  tomcat:
    uri-encoding: utf-8
spring:
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  application:
    name: black-service
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    password: 123456
  datasource:
    url: jdbc:mysql://localhost:3306/az?rewriteBatchedStatements=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456

httpTimeOut: 1500
httpConnectTimeOut: 1500

log:
  home: E://log
sysConf:
    importSize: 2000
    openAsyn: Y
    expireTimeMin: 2
    phoneList:
        - 18101942232
    urlList:
        - http://47.104.73.190:8080/h

